version: 2
jobs:
  test:
    working_directory: ~/Backend/Ennovate_BK
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/Backend
      - run: npm i   
      - run: npm test --forceExit 
workflows:
  version: 2
  test:
    jobs:
      - test
