version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/Backend/Ennovate_BK
    steps:
      - checkout
      - run:
            -command: npm test
            -background
workflows:
  version: 2
  test:
    jobs:
      - test
