version: 2
jobs:
  test:
    working_directory: ~/Backend/Ennovate_BK
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: cd Ennovate_BK, npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
