version: 2
jobs:
  build:
    working_directory: ~/Backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: |
          cd Ennovate_BK
          npm i
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: |
          cd Ennovate_BK
          npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    working_directory: ~/Backend
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          command:|
      cd Ennovate_BK    
      npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
