version: 2
jobs:
  build:
    working_directory: ~/Backend/Ennovate_BK
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    working_directory: ~/Backend/Ennovate_BK
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          command:|
      mkdir -p Backend
      cd Backend
      git clone https://AyahElSamadoni:ayahsamadoni1@github.com/AyahElSamadoni/Backend
      cd /Backend/Ennovate_BK
      npm i
      npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
